# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4aee53c2382002e7df0e644248aad5324aa6777a27391602cd58a200aecdb5625a88217ccc0f9f15ca6fd50836b4f5cbe8c556b64be7835876474770267bdc46

test:
  secret_key_base: aae668c076196030c43454a23091ef1b77a16bf604b060ecdacfe08f6c0b93b4cb0a5bee2acafb11ed7d0f44292c368422de4a94ebeedca3dbced7cdede52e39

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
